name: Build and release ray tracing renderer

on:
  push:
    tags:
      - v*
  
  workflow_dispatch:

jobs:
  build-jar-job:
    name: 'Build and release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
      - name: 'Build with Maven'
        run: cd renderer/ && mvn package spring-boot:repackage
      - name: 'Release jar'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: Renderer release
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: renderer/target/*.jar
