name: Build and release image-conrverter 

on:
  push:
    tags:
      - v*
  
  workflow_dispatch:

jobs:
  build-jar-job:
    name: 'Build and release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 15'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
      - name: 'Build with Maven'
        run: mvn package spring-boot:repackage
      - name: 'Release jar'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: Image converter release
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: image-convertor/target/*.jar
